version: '0.1.0.{build}-{branch}'

configuration:
- Debug
- Release

platform: x64

cache:
- '%USERPROFILE%\.nuget\packages'

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build:
- cmd: copy NUL src\Mofichan.Runner\mofichan.config
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "src\Mofichan.Core" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.Backend" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.Behaviour" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.Runner" -c %CONFIGURATION% --no-dependencies

test_script:
- ps: >-
    $RESULTS_FILE = $ENV:APPVEYOR_BUILD_FOLDER + '\results.xml'

    $OPENCOVER = $ENV:USERPROFILE + '\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe'

    $TARGET = '-target:c:\Program Files\dotnet\dotnet.exe'

    $TARGET_ARGS = '-targetargs:test ' + $ENV:APPVEYOR_BUILD_FOLDER + '\test\Mofichan.Spec -f netcoreapp1.0 -c ' + $ENV:CONFIGURATION

    $FILTER = '-filter:+[Mofichan*]* -[Mofichan.Spec]* -[Mofichan.Tests]* -[Mofichan.Runner]*'

    & $OPENCOVER $TARGET $TARGET_ARGS '-register:user' $FILTER '-mergeoutput' '-oldStyle'

    $TARGET_ARGS = '-targetargs:test ' + $ENV:APPVEYOR_BUILD_FOLDER + '\test\Mofichan.Tests -f netcoreapp1.0 -c ' + $ENV:CONFIGURATION

    & $OPENCOVER $TARGET $TARGET_ARGS '-register:user' $FILTER '-mergeoutput' '-oldStyle'

- ps: >-
    $ENV:PATH = 'C:\\Python34;C:\\Python34\\Scripts;' + $ENV:PATH

    python -m pip install --upgrade pip

    pip install git+git://github.com/codecov/codecov-python.git

    codecov -f $RESULTS_FILE -X gcov