version: '0.1.0.{build}-{branch}'

configuration:
- Debug
- Release

platform: x64

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build:
- cmd: copy NUL src\Mofichan.Runner\mofichan.config
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "src\Mofichan.Core" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.Backend" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.Behaviour" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.Runner" -c %CONFIGURATION% --no-dependencies

test_script:
- dotnet test "test\Mofichan.Spec" -c %CONFIGURATION%

cache:
- '%USERPROFILE%\.nuget\packages'