version: '0.1.0.{build}-{branch}'

branches:
    except:
        - /temp.*/

configuration:
- Release

platform: x64

cache:
- '%USERPROFILE%\.nuget\packages'

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "src\Mofichan.Core" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.DataAccess" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.Backend" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.Behaviour" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mofichan.Runner" -c %CONFIGURATION% --no-dependencies

test_script:
- ps: >-
    $RESULTS_FILE = $ENV:APPVEYOR_BUILD_FOLDER + '\results.xml'

    $OPENCOVER = $ENV:USERPROFILE + '\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe'

    $TARGET = '-target:c:\Program Files\dotnet\dotnet.exe'

    $TARGET_ARGS = '-targetargs:test ' + $ENV:APPVEYOR_BUILD_FOLDER + '\test\Mofichan.Spec -f netcoreapp1.0 -c ' + $ENV:CONFIGURATION

    $FILTER = '-filter:+[Mofichan*]* -[Mofichan.Spec]* -[Mofichan.Tests]* -[Mofichan.Runner]*'

    & $OPENCOVER $TARGET $TARGET_ARGS '-register:user' $FILTER '-mergeoutput' '-oldStyle'

    $TARGET_ARGS = '-targetargs:test ' + $ENV:APPVEYOR_BUILD_FOLDER + '\test\Mofichan.Tests -f netcoreapp1.0 -c ' + $ENV:CONFIGURATION

    & $OPENCOVER $TARGET $TARGET_ARGS '-register:user' $FILTER '-mergeoutput' '-oldStyle' '-returntargetcode'

- ps: >-
    $ENV:PATH = 'C:\\Python34;C:\\Python34\\Scripts;' + $ENV:PATH

    python -m pip install --upgrade pip

    pip install git+git://github.com/codecov/codecov-python.git

    codecov -f $RESULTS_FILE -X gcov

after_test:
- cmd: >-
    set DOCKER_HEADERS="Content-Type: application/json"
    
    set DOCKER_DATA='{"source_type": "Branch", "source_name": "%APPVEYOR_REPO_BRANCH%"}'

    set DOCKER_URL=https://registry.hub.docker.com/u/tagc/mofichan/trigger/fa9e6823-dc8e-46e1-a9bd-0ab96b35fb03/

    curl -H %DOCKER_HEADERS% --data %DOCKER_DATA% -X POST %DOCKER_URL%
