using System;

namespace Mofichan.Core.Interfaces
{
    /// <summary>
    /// Represents an object used to drive pulse-dependant behaviours.
    /// </summary>
    public interface IPulseDriver
    {
        /// <summary>
        /// Occurs when a pulse is generated by this driver.
        /// </summary>
        event EventHandler PulseOccurred;
    }
}